# -*- coding: utf-8 -*-
"""Level 1 Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a5sSax-vjpsOVahpPQNxbVq0u1X_waeo

**Exploratory Data Analysis (EDA) on Retail Sales Data**

**About**

This project focuses on analyzing a retail sales dataset. The main objective is to apply exploratory data analysis (EDA) to identify key patterns, trends, and insights that can support effective decision-making in the retail industry.
"""

from google.colab import drive
        drive.mount('/content/drive')

import pandas as pd

    # Load a CSV file from your Drive
    df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/retail_sales.csv")

"""**Data Loading and Cleaning-**

"""

df['Date'] = pd.to_datetime(df['Date'])
df = df.drop_duplicates()
df = df.fillna(0)   # example handling

# Summary statistics
print("Summary Statistics:")
print(df.describe())

# Number of unique customers
print("\nUnique Customers:", df['Customer ID'].nunique())

# Top 10 products by frequency
print("\nTop 10 Products:")
print(df['Product Category'].value_counts().head(10))

print(df)

# Show first 5 rows
print(df.head())

# Show first 10 rows
print(df.head(10))

# Show last 5 rows
print(df.tail())

# Show DataFrame shape (rows, columns)
print("Shape of DataFrame:", df.shape)

df.describe()
df['Customer ID'].nunique()
df['Product Category'].value_counts().head(10)

df.groupby(df['Date'].dt.to_period('M'))['Total Amount'].sum().plot(kind='line')

df.groupby('Customer ID')['Total Amount'].sum().sort_values(ascending=False).head(10)

df.groupby('Product Category')['Total Amount'].sum().sort_values(ascending=False).head(10)

import seaborn as sns
import matplotlib.pyplot as plt

sns.barplot(x='Product Category', y='Total Amount', data=df.nlargest(10, 'Total Amount'))
plt.show()